Added hw1
setday/HSE_ML_HW2024 pull request #1
Opened 2024-01-28 13:40 UTC by setday

2024-02-03 11:14 UTC, svkov requested changes
Ставлю 0.4 и + за хард. Поправь в первой медиану и зачту полностью.

2024-02-03 11:14 UTC, svkov commented on hw_1/dota_hero_stats.csv
Данные надо убрать из репо. И лежать они должны в папке data, прочитай внимательнее как нужно оформить репозиторий

2024-02-03 11:14 UTC, svkov commented on hw_1/hw_1.ipynb
> +    "        \"median\": sorted_arr[ n // 2 ],\n",
Медиана считается не так
https://en.wikipedia.org/wiki/Median

2024-02-03 11:14 UTC, svkov commented on hw_1/hw_1.ipynb
> +    "Сравнение по `roles` будем проверять как относительное онколение различных ролей от общего числа ролей $\\frac{count(legs_1 \\bigtriangleup legs_2)}{count(roles_1) + count(roles_2)}$\n",
Что такое онколение?) Я бы подумал, что это опечатка, но дважды в тексте встречается. Поиск ничего не выдает на это слово

2024-02-03 11:14 UTC, svkov commented on hw_1/hw_1.ipynb
> +    "Веса отдаления распределим так:\n",
Почему такие веса? Пробовал ли с какими-то другими весами запускать, получались ли другие результаты?

2024-02-03 11:14 UTC, svkov commented on hw_1/hw_1.ipynb
> +    "        diffs[ 'roles' ] = len( set( hero_1[ 'roles' ] ) ^ set( hero_2[ 'roles' ] ) ) / ( len( hero_1[ 'roles' ] ) + len( hero_2[ 'roles' ] ) )\n",
Кажется, такие вычисления лучше выносить в отдельные функции. А еще лучше форматировать код по PEP-8 (если влом руками редактировать, можно писать ноутбуки в vs code, и там настроить линтер)

2024-02-03 11:14 UTC, svkov commented on hw_1/hw_1.ipynb
> +    "    return (1 + result) ** -0.5\n",
А почему формула поменялась?) В тексте прописана -1 степень, а тут -0.5

2024-02-07 11:30 UTC, setday commented on hw_1/hw_1.ipynb
> +    "    return (1 + result) ** -0.5\n",
Корень + обратное в одной формуле)

Правда корень не из того взял)

2024-02-07 11:31 UTC, setday commented on hw_1/hw_1.ipynb
> +    "        diffs[ 'roles' ] = len( set( hero_1[ 'roles' ] ) ^ set( hero_2[ 'roles' ] ) ) / ( len( hero_1[ 'roles' ] ) + len( hero_2[ 'roles' ] ) )\n",
Я и пишу в VSCode, просто ненавижу всей душой PEP-8 и уважаю лишь C# style)

2024-02-07 11:44 UTC, setday commented on hw_1/hw_1.ipynb
> +    "Сравнение по `roles` будем проверять как относительное онколение различных ролей от общего числа ролей $\\frac{count(legs_1 \\bigtriangleup legs_2)}{count(roles_1) + count(roles_2)}$\n",
онколение - это древне коряво-русское слово, обычное возникающее вследствие безграмотности человека, его написавшего, обозначающее отклонение :)

2024-02-07 11:45 UTC, setday commented on hw_1/hw_1.ipynb
> +    "        \"median\": sorted_arr[ n // 2 ],\n",
Исправлено

2024-02-07 11:45 UTC, setday commented on hw_1/hw_1.ipynb
> +    "Сравнение по `roles` будем проверять как относительное онколение различных ролей от общего числа ролей $\\frac{count(legs_1 \\bigtriangleup legs_2)}{count(roles_1) + count(roles_2)}$\n",
Исправлено

2024-02-07 11:46 UTC, setday commented on hw_1/hw_1.ipynb
> +    "        diffs[ 'roles' ] = len( set( hero_1[ 'roles' ] ) ^ set( hero_2[ 'roles' ] ) ) / ( len( hero_1[ 'roles' ] ) + len( hero_2[ 'roles' ] ) )\n",
Исправлено частично. Если надо, могу всё под PEP-8 писать

2024-02-07 11:46 UTC, setday commented on hw_1/hw_1.ipynb
> +    "    return (1 + result) ** -0.5\n",
Исправлено

2024-02-07 11:49 UTC, setday commented on hw_1/dota_hero_stats.csv
Вроде исправил, но не очень понял, где найти гайд по оформлению *вроде в jupiter-ах его нет и в чатике тоже :( )

2024-02-07 12:10 UTC, setday commented on hw_1/hw_1.ipynb
> +    "Веса отдаления распределим так:\n",
10 выбрана как величина, относительно которой строятся другие веса (можно было бы просто поделить все веса на 10 или умножить. Да, это повлияло бы на величину метрики, однако порядок схожести бы не изменился.
0.1 выбрана так, чтобы не вносить вклада при хоть каком-то совпадении характеристик, влияющих на механику (так, только при 100 различных характеристик roles ноги начинают иметь значение)
Ну а 3 выбрано так, что второстепенные характеристики начинали играть роль только при существенном различии первостепенных (при отклонении более 70%).

По поводу изменения весов: если говорить о максимально схожих персонажах, то при моей логике сравнения фичей, веса не имеют значения, т.к. `Keeper of the Light` и `Crystal Maiden` полностью совпадают по критериям сравнения, а значит коэффициенты всегда будут домножаться на 0. А вот максимально различные изменятся. Так, если в приоритет поставить ноги, то максимально различными станут `Zeus` и `Naga Siren` (несмотря на то, что у одного из них не 10 ног, а всего 2, мне кажется такая метрика корректной, т.к. тут идёт скорее сравнение по характеристики `летающий`, `ходячий`).

2024-02-10 08:39 UTC, svkov commented on hw_1/dota_hero_stats.csv
https://github.com/svkov/hse_ml_course_2024/blob/main/README.md#как-оформлять-репозиторий

2024-02-10 08:42 UTC, svkov approved these changes
Почитай про оформление. В остальном все ок!

2024-02-10 10:48 UTC, merged