Add hw-3
setday/HSE_ML_HW2024 pull request #3
Opened 2024-03-05 15:00 UTC by setday

2024-03-09 11:37 UTC, svkov requested changes
Поправь метрику и доделай хард. Ставлю пока 0.4

2024-03-09 11:37 UTC, svkov commented on notebooks/03-homework.ipynb
1. Мы не можем использовать accuracy для несбалансированных классов. Не важно сколько у нас данных. мы можем легко пропустить, что мы вообще никак не учитываем все малопредставленные классы. Выбери другую метрику. Значения там действительно будут близкими, но в другой задаче это может быть не так.
2. В харде нужно получить график в координатах (кол-во семплов для обучения, качество на нем). Такую кривую нужно построить с использованием аугментации и без нее. Гипотеза - используя аугментацию можно размечать меньше данных, и получать такую же точность модели. Нам хочется понять какой размен качества на деньги существует (каждая размеченная картинка стоит денег).

2024-03-16 12:55 UTC, svkov approved these changes
easy и medium зачел, больше исправления не принимаются

2024-03-22 11:08 UTC, Skripkon commented
**0.0 
everything is terrible!**

2024-04-20 20:04 UTC, merged