Hw 6
setday/HSE_ML_HW2024 pull request #6
Opened 2024-04-25 12:14 UTC by setday

2024-04-25 12:15 UTC, setday commented
hw-6 пока не готова. Проверять не надо.

2024-04-27 12:38 UTC, svkov requested changes
На medium сделано больше, чем нужно, и сделано неправильно. Но раз тебя интересует тема регрессии, то пересчитай модели классификации с метрикой регрессии и посмотри, насколько результаты похожи на f1.

Пока что только easy засчитываю)

2024-04-27 12:38 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "def plot_bar(y, loc='left', relative=True):\n",
А чем тебе стандартный hist не угодил? Если хотелось именно в процентах посчитать, есть параметр `density`

2024-04-27 12:38 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "tfid_result = tfid.fit_transform(df['text']).toarray()"
тут ты переобучаешься - сразу обучаешься и на трейне и на тесте

2024-04-27 12:38 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "def show_accuracy(y_test, y_pred):\n",
почему функция называется show_accuracy, а внутри используешь f1?

misleading название, сложно читать такое)

2024-04-27 12:38 UTC, svkov commented on notebooks/06-homework.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABL4AAAUPCAYAAAC4AyloAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAACEGElEQVR4nOz
а что ты тут предсказываешь регрессией?

деревья усредняют значения в листьях, и на выходе ты можешь получить невалидное значение (например, 2.2)
так можно делать, но нужно обоснование, почему ты захотел так сделать, и, наверное, не через f1 такое измерять надо

в классе мы как-то решали задачу классификации, а метрику брали из регрессии. такой трюк тут можно проворачивать без вопросов, но модель все-таки лучше брать классификации

2024-04-27 12:38 UTC, svkov commented on notebooks/06-homework.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABL4AAAUPCAYAAAC4AyloAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAACEGElEQVR4nOz
пока что ты просто подобрал несколько отзывов, не хватает обоснование, какие слова стоит использовать, а какие нет. посмотри на importance модели, там разгадка

2024-05-02 13:01 UTC, setday commented on notebooks/06-homework.ipynb
> +    "def show_accuracy(y_test, y_pred):\n",
Ну, хотелось абстрагировать функцию от метрики. `accuracy` тут используется не в значении метрики, в значении `точность модели`

2024-05-18 12:06 UTC, svkov approved these changes
Зачтено

2024-05-18 12:06 UTC, svkov commented on notebooks/06-homework.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABL4AAAUPCAYAAAC4AyloAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAACA5ElEQVR4nOz
> это было реально очевидно ввиду структуры модели

если бы в исходных данных было много примеров с иронией, модель могла бы негативные слова записать в позитивные. так мы лишний раз убедились, как именно работает модель.

плюс здесь довольно очевидная предметная область. в 8 домашке, например, если поставить себе цель обмануть модель, то без заглядывания в importance это будет сделать проблематично.

2024-05-18 12:06 UTC, svkov commented on notebooks/06-homework.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABL4AAAUPCAYAAAC4AyloAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAACA5ElEQVR4nOz
мы еще никаких нейронок не обучали =)

2024-05-18 12:06 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "def show_regression_model_perfection_metrics(y_test, y_pred):\n",
вот эту функцию можно использовать, чтобы измерять качество вообще всех моделей в этой задаче. а модели регрессии использовать тут мало смысла, заранее известно, что они будут хуже работать, чем модели классификации.

2024-05-22 17:36 UTC, merged